(ql:quickload :svg :silent t)

(in-package #:svg)

(defun test-path ()
  (format t "~%=== Test Path ===~%")
  (with-svg ("test/test-path.svg" 400 200)
    (path ((moveto (complex 50 50))
           (lineto (complex 100 50))
           (quadto (complex 125 20) (complex 150 50))
           (lineto (complex 200 50))
           (closepath))
          :stroke "green" :fill "none" :stroke-width 2)
    (path ((moveto (complex 50 100))
           (curveto (complex 80 80) (complex 120 60) (complex 150 100))
           (closepath))
          :stroke "blue" :fill "none" :stroke-width 2)
    (path ((moveto (complex 50 150))
           (arc (complex 20 20) (complex 100 150) :x-axis-rotation 0 :large-arc-flag 1 :sweep-flag 1)
           (lineto (complex 150 150))
           (closepath))
          :stroke "red" :fill "none" :stroke-width 2))
  (format t "Output: test/test-path.svg~%"))

(test-path)
