(ql:quickload :svg :silent t)

(in-package #:svg)

(defun test-path ()
  (format t "~%=== Test Path ===~%")
  (with-svg ("test/test-path.svg" 400 200)
    (rect (p 0 0) 400 200 :fill "white")
    (path ((moveto (p 50 50))
           (lineto (p 100 50))
           (quadto (p 125 20) (p 150 50))
           (lineto (p 200 50))
           (closepath))
          :stroke "green" :fill "none" :stroke-width 2)
    (path ((moveto (p 50 100))
           (curveto (p 80 80) (p 120 60) (p 150 100))
           (closepath))
          :stroke "blue" :fill "none" :stroke-width 2)
    (path ((moveto (p 50 150))
           (arc (p 20 20) (p 100 150) :x-axis-rotation 0 :large-arc-flag 1 :sweep-flag 1)
           (lineto (p 150 150))
           (closepath))
          :stroke "red" :fill "none" :stroke-width 2))
  (format t "Output: test/test-path.svg~%"))

(test-path)
