;;; ============================================================
;;; CL-SVG 生成脚本模板（svg-gen skill）
;;;
;;; 用法：
;;;   1. 复制本文件为 generate.lisp（或任意名字）
;;;   2. 在 with-svg 的 body 中填写要绘制的图形
;;;   3. 运行：
;;;        sbcl --non-interactive --load generate.lisp [-- /path/to/output.svg]
;;;      不传路径时输出到默认 /tmp/output.svg
;;; ============================================================

(ql:quickload :svg :silent t)
(in-package #:svg)

;;; 输出路径：命令行参数（-- 之后）优先，否则用默认值
(defun script-output ()
  "取 `--` 之后的第一个参数作为输出路径，缺省为 /tmp/output.svg。"
  (or (cadr (member "--" sb-ext:*posix-argv* :test #'string=))
      "/tmp/output.svg"))

(defparameter *output* (script-output))

(defun draw ()
  ;; with-svg 会在 body 结束后自动写 <defs> 与 </svg>
  (with-svg (*output* 500 400)
    ;; ---- 从这里开始填写绘制内容 ----
    ;; 画布背景（可选）
    (rect (p 0 0) 500 400 :fill "white")

    ;; 形状
    (circle (p 250 160) 60 :fill "#3498db")
    (rect (p 190 240) 120 50 :rx 8 :fill "#e74c3c")

    ;; 路径（三角形）
    (path ((moveto (p 250 300))
           (lineto (p 280 340))
           (lineto (p 220 340))
           (closepath))
          :fill "#f1c40f")

    ;; 文本
    (text (p 250 380) "Generated by CL-SVG"
          :font-size 16 :text-anchor "middle" :fill "#333")
    ;; ---- 到这里结束 ----
    ))

(draw)
(format t "Generated ~a~%" *output*)
