#!/usr/bin/env python3
"""Generate src/latex-extra-glyph-paths.lisp from Latin Modern Math.

The vendored glyph table (src/tex/glyph-paths.lisp) covers the parenthesis,
bracket and brace delimiter chains, but not the *variants* Latin Modern Math
ships for the ceiling, floor and angle brackets -- the .v2/.v4/.v6/.v7 designs
cmex10 uses for \\left\\lceil ... \\right\\rceil and friends. Without an outline
the renderer falls back to previewing the base Unicode glyph at its natural
10pt size and, because the preview transform has no *LM-GLYPH-INK* entry for
those six code points either, leaves it unscaled: a \\lfloor inside an 18pt
fence came out as a 10pt glyph drawn high, next to the fraction it should
enclose.

The same table was missing cmex10's contour integral (72/73, what \\oint uses),
which therefore previewed as the raw font slot -- the letter 'I'.

The outlines below are Latin Modern Math's own (upm 1000, y up), in the same
format as glyph-paths.lisp: NAME ADVANCE INK-BOX . PATH. Each variant's ink is
exactly as tall as the CM box it is stacked for (12/18/24/30pt at 10pt type),
so drawing it at the design size puts it where cmex10 draws its own piece.

Usage: python3 tools/gen-lm-extra-glyph-paths.py [LATINMODERN-MATH.OTF]
"""

import sys

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

DEFAULT_FONT = "/usr/share/texmf/fonts/opentype/public/lm-math/latinmodern-math.otf"
OUT = "src/latex-extra-glyph-paths.lisp"

# the ceilings, floors and angles, in cmex10's own order: left, right
FAMILIES = [("uni2308", "uni2309", "ceiling"),    # \lceil \rceil
            ("uni230A", "uni230B", "floor"),      # \lfloor \rfloor
            ("uni27E8", "uni27E9", "angle")]      # \langle \rangle
VARIANTS = (".v2", ".v4", ".v6", ".v7")           # 12, 18, 24, 30pt

# cmex10's contour integral: 72 is the text-size design, 73 the display one,
# and Latin Modern Math keeps both as `contourintegral' (see CMEX_NAMES in
# src/latex-star.lisp for the slot -> name mapping).
CONTOUR = ("contourintegral", "contourintegral.v1")

# cmsy10's \not slash (54, zero advance, overlaid on the base). Latin Modern
# Math has no big solidus at all -- just the text slash -- so \neq previewed
# whichever glyph the browser fell back to, at the wrong size and angle.
SLASHES = ("slash",)

# cmex10's other large operators: the engine's own glyph table only ever named
# \sum, \prod and \int, so every other operator slot previewed as a raw font
# code or the wrong symbol. Latin Modern keeps them as these glyphs (text and
# display sizes); the slots are cmex10's own, from LaTeX's \mathchar tables.
OPERATORS = ("uni2A06",    # \bigsqcup
             "uni2A00",    # \bigodot
             "uni2A01",    # \bigoplus
             "uni2A02",    # \bigotimes
             "uni22C3",    # \bigcup
             "uni22C2",    # \bigcap
             "uni2A04",    # \biguplus
             "uni22C0",    # \bigwedge
             "uni22C1",    # \bigvee
             "uni2210")    # \coprod
OPERATOR_SIZE_SUFFIXES = ("", ".v1")   # 10pt (text) and 16pt (display) designs


def glyph_entry(glyphs, name):
    glyph = glyphs[name]
    bounds = BoundsPen(glyphs)
    glyph.draw(bounds)
    x0, y0, x1, y1 = (int(round(v)) for v in bounds.bounds)
    pen = SVGPathPen(glyphs)
    glyph.draw(pen)
    return '    ("%s" %d (%d %d %d %d)\n     . "%s")' % (
        name, glyph.width, x0, y0, x1, y1, pen.getCommands())


def main():
    font_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_FONT
    glyphs = TTFont(font_path).getGlyphSet()
    lines = [
        ";;;; latex-extra-glyph-paths.lisp --- generated by",
        ";;;; tools/gen-lm-extra-glyph-paths.py from Latin Modern Math; do not edit.",
        ";;;;",
        ";;;; Outlines (upm 1000, y up) that src/tex/glyph-paths.lisp does not",
        ";;;; carry: the ceiling/floor/angle bracket variants and the contour",
        ";;;; integral. See the generator for why the LaTeX front end needs them.",
        "",
        "(in-package #:svg)",
        "",
        "(defparameter *latex-extra-glyph-paths*",
        "  '(",
    ]
    for left, right, label in FAMILIES:
        lines.append("    ;; %s" % label)
        for base in (left, right):
            for suffix in VARIANTS:
                lines.append(glyph_entry(glyphs, base + suffix))
    lines.append("    ;; contour integral (\\oint)")
    for name in CONTOUR:
        lines.append(glyph_entry(glyphs, name))
    lines.append("    ;; the \\not slash (cmsy10 54)")
    for name in SLASHES:
        lines.append(glyph_entry(glyphs, name))
    lines.append("    ;; the other large operators, text and display size")
    for base in OPERATORS:
        for suffix in OPERATOR_SIZE_SUFFIXES:
            lines.append(glyph_entry(glyphs, base + suffix))
    lines += ["    ))",
              "",
              ""]
    with open(OUT, "w") as out:
        out.write("\n".join(lines))
    print("wrote", OUT, "with",
          6 * len(VARIANTS) + len(CONTOUR) + len(OPERATORS) * len(OPERATOR_SIZE_SUFFIXES),
          "outlines")


if __name__ == "__main__":
    main()
